import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { loadEnv } from "vite";

const SW_PATH = "public/firebase/firebase-messaging-sw.js";
const FIREBASE_VERSION = "12.13.0";

function buildMessagingSwContent(root: string, mode: string): string {
  const env = loadEnv(mode, root, "");
  const firebaseConfig = {
    apiKey: env.VITE_FIREBASE_APIKEY ?? "",
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? "",
    projectId: env.VITE_FIREBASE_PROJECT_ID ?? "",
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET ?? "",
    messagingSenderId: env.VITE_FIREBASE_MESSAGE_SENDER_ID ?? "",
    appId: env.VITE_FIREBASE_APP_ID ?? "",
    ...(env.VITE_FIREBASE_MEASUREMENT_ID
      ? { measurementId: env.VITE_FIREBASE_MEASUREMENT_ID }
      : {}),
  };

  return `/* Generated by vite — do not edit. */
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title =
    payload.notification?.title || payload.data?.title || "New contact message";
  const body =
    payload.notification?.body || payload.data?.body || "";
  const messageId = payload.data?.messageId;

  return self.registration.showNotification(title, {
    body,
    icon: payload.notification?.icon || "/favicon.png",
    badge: "/favicon.png",
    tag: messageId ? "message:" + messageId : undefined,
    data: payload.data || {},
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const targetUrl = event.notification.data?.url || "/";

  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((list) => {
      for (const client of list) {
        if ("focus" in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    }),
  );
});
`;
}

function writeMessagingSw(root: string, mode: string) {
  const outPath = path.join(root, SW_PATH);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, buildMessagingSwContent(root, mode), "utf8");
}

/** Writes `public/firebase/firebase-messaging-sw.js` from Vite env (FCM background handler). */
export function firebaseMessagingSwPlugin(): Plugin {
  let root = process.cwd();
  let mode = "production";

  return {
    name: "firebase-messaging-sw",
    configResolved(config) {
      root = config.root;
      mode = config.mode;
    },
    buildStart() {
      writeMessagingSw(root, mode);
    },
    configureServer(server) {
      const write = () => writeMessagingSw(server.config.root, server.config.mode);
      write();
      server.watcher.on("change", (file) => {
        if (path.basename(file).startsWith(".env")) {
          write();
        }
      });
    },
  };
}
