import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { loadEnv } from "vite";

/** Imported by the Workbox PWA service worker via `workbox.importScripts`. */
const SW_PATH = "public/firebase-messaging-sw.js";
const FIREBASE_VERSION = "12.13.0";

function buildMessagingSwContent(root: string, mode: string): string {
  const env = loadEnv(mode, root, "");
  const firebaseConfig = {
    apiKey: env.VITE_FIREBASE_APIKEY ?? "",
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? "",
    projectId: env.VITE_FIREBASE_PROJECT_ID ?? "",
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET ?? "",
    messagingSenderId: env.VITE_FIREBASE_MESSAGE_SENDER_ID ?? "",
    appId: env.VITE_FIREBASE_APP_ID ?? "",
    ...(env.VITE_FIREBASE_MEASUREMENT_ID
      ? { measurementId: env.VITE_FIREBASE_MEASUREMENT_ID }
      : {}),
  };

  return `/* Generated by vite — imported into the PWA service worker. Do not register separately. */
function safeInAppUrl(rawUrl) {
  try {
    const url = new URL(rawUrl, self.location.origin);
    if (url.origin !== self.location.origin) {
      return self.location.origin + "/";
    }
    return url.pathname + url.search + url.hash;
  } catch {
    return "/";
  }
}

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const targetUrl = safeInAppUrl(event.notification.data?.url || "/");

  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((list) => {
      for (const client of list) {
        if ("focus" in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    }),
  );
});

importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const title = data.title || payload.notification?.title || "New contact message";
  const body = data.body || payload.notification?.body || data.preview || "";
  const messageId = data.messageId;
  const url = data.url || "/";

  const options = {
    body,
    icon: payload.notification?.icon || "/favicon.png",
    badge: "/favicon.png",
    tag: messageId ? "message:" + messageId : undefined,
    data: { ...data, url },
  };

  return self.registration.showNotification(title, options);
});
`;
}

function writeMessagingSw(root: string, mode: string) {
  const outPath = path.join(root, SW_PATH);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, buildMessagingSwContent(root, mode), "utf8");
}

/** Writes `public/firebase-messaging-sw.js` from Vite env (FCM background handler for Workbox SW). */
export function firebaseMessagingSwPlugin(): Plugin {
  let root = process.cwd();
  let mode = "production";

  return {
    name: "firebase-messaging-sw",
    configResolved(config) {
      root = config.root;
      mode = config.mode;
    },
    buildStart() {
      writeMessagingSw(root, mode);
    },
    configureServer(server) {
      const write = () => {
        writeMessagingSw(server.config.root, server.config.mode);
      };
      write();
      server.watcher.on("change", (file) => {
        if (path.basename(file).startsWith(".env")) {
          write();
        }
      });
    },
  };
}
